spring:
  # Application Info
  application:
    name: NewMit

  # MVC Info
  mvc:
    view:
      prefix: /WEB-INF/jsp/views
      suffix: .jsp

  # DB Connection Info
  datasource:
    url: jdbc:mysql://192.168.114.128:3306/jd
    username: jd2
    password: 1Q2W3e4r!!
    driver-class-name: com.mysql.jdbc.Driver
  # JPA Info
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

  # MyBatis Configuration
  mybatis:
    mapper-locations: classpath:/mappers/**/*.xml  # Locations of MyBatis mapper XML files

  # application-oauth import
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

# Server Info
server:
  port: 9090  # Specifies the port on which the server will run

jwt:
  issuer: HeoZuo
  secret_key: HeoZuo-NewMit



