spring:
  # Application Info
  application:
    name: NewMit

  # MVC Info
  mvc:
    view:
      prefix: /WEB-INF/jsp/views
      suffix: .jsp

  # file
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  # profiles:
  #  active: dev

  # DB Connection Info
  datasource:
    url:
    username: NMu
    password: 1q2w3e4r!!
    driver-class-name: com.mysql.jdbc.Driver

  # JPA Info
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true # ANSI 코드에 색을 나타낸다
        use_sql_comments: true # SQL 내부에 /* */ 주석 추가
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

  # application-oauth import
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
          kakao:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: https://newmit.false.kr/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id:
            client-secret: 
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: https://newmit.false.kr/login/oauth2/code/naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# Server Info
server:
  port: 8080  # Specifies the port on which the server will run
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      pattern: '%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b'

  # MyBatis Configuration
  # Locations of MyBatis mapper XML files
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml

jwt:
  issuer: HeoZuo
  secret_key: HeoZuo-NewMit

directory:
  fileDir: /NewMit/SaveFile/