spring:
  # Application Info
  application:
    name: NewMit

  # MVC Info
  mvc:
    view:
      prefix: /WEB-INF/jsp/views
      suffix: .jsp

  # DB Connection Info
  datasource:
    url: jdbc:mysql://192.168.114.128:3306/jd
    username: jd2
    password: 1Q2W3e4r!!
    driver-class-name: com.mysql.jdbc.Driver

    jpa:
      properties:
        hibernate:
          show_sql: true

  profiles:
    include: oauth

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 21475556791-2cgd5ot9k19ko12ucvosjsabhj0peova.apps.googleusercontent.com
            client-secret: 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
          scope:
            -email
            -profile

# Server Info
server:
  port: 8080  # Specifies the port on which the server will run

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml  # Locations of MyBatis mapper XML files
