spring:
  # Application Info
  application:
    name: NewMit

  # MVC Info
  mvc:
    view:
      prefix: /WEB-INF/jsp/views
      suffix: .jsp

  # DB Connection Info
  datasource:
    url: jdbc:mysql://192.168.114.128:3306/jd
    username: jd2
    password: 1Q2W3e4r!!
    driver-class-name: com.mysql.jdbc.Driver

  profiles:
    include: oauth

# Server Info
server:
  port: 8080  # Specifies the port on which the server will run

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml  # Locations of MyBatis mapper XML files
