

-- 공통코드 테이블
CREATE TABLE TB_COMMON_CODE (
    COMMON_CODE_CD VARCHAR(6) COMMENT '공통코드' PRIMARY KEY,
    COMMON_CODE_NM VARCHAR(20) COMMENT '공통코드명'
);

-- 회원정보 테이블
CREATE TABLE TB_MEMBERS_INFO (
    MB_NO INT(10) COMMENT '회원 넘버' PRIMARY KEY,
    MB_ID VARCHAR(15) COMMENT '회원 아이디' NOT NULL,
    MB_PW VARCHAR(100) COMMENT '회원 비번' NOT NULL,
    MB_NM VARCHAR(50) COMMENT '회원 이름' NOT NULL,
    MB_BIRTH_DATE VARCHAR(8) COMMENT '회원 생년월일',
    MB_GENDER VARCHAR(1) COMMENT '회원 성별',
    MB_PHONE_NUMBER VARCHAR(11) COMMENT '회원 폰 번호' NOT NULL,
    MB_REGISTER_DATE DATE COMMENT '회원 가입 일자' NOT NULL,
    MB_REGISTER_IP VARCHAR(15) COMMENT '회원 가입 아이피' NOT NULL,
    MB_UPDATE_DATE DATE COMMENT '회원 업데이트 일자' NOT NULL,
    MB_UPDATE_IP VARCHAR(15) COMMENT '회원 업데이트 아이피' NOT NULL
);

-- 서비스 고객센터 테이블
CREATE TABLE TB_CUSTOMER_SERVICE_COMPLAINTS (
    MB_NO INT(10) NOT NULL COMMENT '등록자',
    CUSTOMER_SERVICE_COMPLAINT_NO INT(10) COMMENT '고객센터 문의 넘버',
    CUSTOMER_SERVICE_COMPLAINT_SUBJECT VARCHAR(50) COMMENT '고객센터 문의 제목' NOT NULL,
    CUSTOMER_SERVICE_COMPLAINT_CONTENTS VARCHAR(5000) COMMENT '고객센터 문의 내용' NOT NULL,
    CUSTOMER_SERVICE_COMPLAINT_REGISTER_DATE DATE COMMENT '고객센터 문의 등록 일자' NOT NULL,
    CUSTOMER_SERVICE_COMPLAINT_REGISTER_IP VARCHAR(15) COMMENT '고객센터 문의 등록 아이피' NOT NULL,
    CUSTOMER_SERVICE_COMPLAINT_UPDATE_DATE DATE COMMENT '고객센터 문의 업데이트 일자' NOT NULL,
    CUSTOMER_SERVICE_COMPLAINT_UPDATE_IP VARCHAR(15) COMMENT '고객센터 문의 업데이트 아이피' NOT NULL,
    PRIMARY KEY (MB_NO, CUSTOMER_SERVICE_COMPLAINT_NO)
);

-- 서비스 고객센터 첨부 이미지 테이블
CREATE TABLE TB_CUSTOMER_SERVICE_COMPLAINT_ATTACHED_IMAGES (
    CUSTOMER_SERVICE_COMPLAINT_NO INT(10) COMMENT '고객센터 문의 넘버' PRIMARY KEY,
    CUSTOMER_SERVICE_COMPLAINT_ATTACHED_IMAGE_NO INT(10) COMMENT '고객센터 문의 이미지 넘버' NOT NULL
);

-- 보유식자재 테이블
CREATE TABLE TB_INGREDIENTS_OWNED (
    MB_NO INT(10) COMMENT '회원 넘버',
    INGREDIENT_OWNED_NO INT(10) COMMENT '보유식자재넘버',
    INGREDIENT_OWNED_NM VARCHAR(20) COMMENT '보유 식자재 이름' NOT NULL,
    INGREDIENT_OWNED_EXPIRATION_DATE VARCHAR(8) COMMENT '보유 식자재 유통기한' NOT NULL,
    INGREDIENT_OWNED_IMAGE_ID VARCHAR(10) COMMENT '보유 식자재 이미지 아이디' NOT NULL,
    INGREDIENT_OWNED_REGISTER_DATE DATE COMMENT '보유 식자재 등록 일자' NOT NULL,
    INGREDIENT_OWNED_REGISTER_IP VARCHAR(15) COMMENT '보유 식자재 등록 아이피' NOT NULL,
    PRIMARY KEY(MB_NO, INGREDIENT_OWNED_NO)
);

-- 레시피 테이블
CREATE TABLE TB_RECIPE (
    MB_NO INT(10) COMMENT '등록자',
    RECIPE_NO INT(10) COMMENT '레시피 넘버',
    RECIPE_NM VARCHAR(25) COMMENT '레시피 명' NOT NULL,
    RECIPE_MAIN_IMAGE_ID VARCHAR(10) COMMENT '레시피 메인 이미지 아이디' NOT NULL,
    RECIPE_REGISTER_DATE DATE COMMENT '레시피 등록 일자' NOT NULL,
    RECIPE_REGISTER_IP VARCHAR(15) COMMENT '레시피 등록 아이피' NOT NULL,
    RECIPE_UPDATE_DATE DATE COMMENT '레시피 업데이트 일자' NOT NULL,
    RECIPE_UPDATE_IP VARCHAR(15) COMMENT '레시피 업데이트 아이피' NOT NULL,
    PRIMARY KEY(MB_NO, RECIPE_NO)
);

-- 레시피 평점 테이블
CREATE TABLE TB_RECIPE_RATING (
    RECIPE_NO INT(10) COMMENT '레시피 넘버',
    MB_NO INT(10) COMMENT '등록자 넘버',
    RECIPE_RATING_SCORE INT(1) COMMENT '레시피 평점' NOT NULL,
    RECIPE_RATING_REGISTER_DATE DATE COMMENT '레시피 평점 등록 일자' NOT NULL,
    RECIPE_RATING_REGISTER_IP VARCHAR(15) COMMENT '레시피 평점 등록 아이피' NOT NULL,
    RECIPE_RATING_UPDATE_DATE DATE COMMENT '레시피 평점 업데이트 일자' NOT NULL,
    RECIPE_RATING_UPDATE_IP VARCHAR(15) COMMENT '레시피 평점 업데이트 아이피' NOT NULL,
    PRIMARY KEY(RECIPE_NO, MB_NO)
);

-- 조리 과정 레시피 테이블
CREATE TABLE TB_COOKING_PROCESS (
    RECIPE_NO INT(10) COMMENT '레시피 넘버',
    RECIPE_STEP_NO INT(3) COMMENT '레시피 스텝 넘버' NOT NULL,
    RECIPE_STEP_IMAGE_ID VARCHAR(10) COMMENT '레시피 스텝 이미지 아이디' NOT NULL,
    RECIPE_STEP_EXPLANATION VARCHAR(100) COMMENT '레시피 스텝 설명' NOT NULL,
    RECIPE_STEP_REGISTER_DATE DATE COMMENT '레시피 스텝 등록 일자' NOT NULL,
    RECIPE_STEP_REGISTER_IP VARCHAR(15) COMMENT '레시피 스텝 등록 아이피' NOT NULL,
    RECIPE_STEP_UPDATE_DATE DATE COMMENT '레시피 스텝 변경 일자' NOT NULL,
    RECIPE_STEP_UPDATE_IP VARCHAR(15) COMMENT '레시피 스텝 변경 아이피' NOT NULL,
    PRIMARY KEY(RECIPE_NO, RECIPE_STEP_NO)
);

-- 레시피 기록 테이블
CREATE TABLE TB_RECIPE_HISTORY (
    MB_NO INT(10) COMMENT '조회자',
    RECIPE_NO INT(10) COMMENT '레시피 넘버',
    VIEW_DATE DATE COMMENT '조회 일자' NOT NULL,
    PRIMARY KEY(MB_NO, RECIPE_NO)
);